### PR TITLE
feat(popover): Add bsEnabled option

### LINKED ISSUE #2156: feat(popover): Add bsEnabled (data-bs-enabled in template) option
Presently the tooltip has bsEnabled support but no other components do. It is a handy feature. Please migrate it to the other components.

### PR DESCRIPTION
**Pull request by matthewdfleming**
add the ability to enable and disable the popover trigger.

closes: #2156

### CODE REVIEW

**Comment by DaleWebb** [comment]
Thanks!

Could you change the description and title of the PR to match the contribution guidelines.

**Comment by matthewdfleming** [comment]
lmk if I still don't have the title/description correct..

**Comment by DaleWebb** [comment]
Yep it's fine, cheers!

**Comment by mgcrea** [comment]
Thanks for the PR.

**Pull request merged**
