### PR TITLE
Support `data-` prefix for ng-bind reference

### PR DESCRIPTION
**Pull request by monokrome**

### CODE REVIEW

**Comment by mgcrea** [comment]
Should be harmonized with the tooltip.

**Comment by monokrome** [comment]
@mgcrea Sorry, I think that I may be missing some context here?

**Comment by juliusosokinas** [comment]
Is there an issue opened I could refer to? I'm having the same problem, when data-ng-bind does not work as expected.

**Comment by monokrome** [comment]
@mgcrea What's up?

**Comment by DaleWebb** [comment]
I think he meant that the change should also be made to the tooltip component

**Pull request closed without merging**
