### PR TITLE
Typeahead refactor select mode and model update

### PR DESCRIPTION
**Pull request by vmlf01**
Added some more tests and fixes on top of @ruifortes PR #1310, but still have some problems when testing in docs pages:
- Selecting item with ENTER key doesn't update ngModel bindings
- Icon input (minLength = 0) doesn't show options dropdown until you type something, then it will behave as expected
- In Firefox, when selecting an icon with the mouse the ngModel will be set to the item, but then pressing tab or clicking outside, the ngModel will be updated again with the input text (there were already some previous issue reports related to this: #652, #1011)
- In Angular 1.2, when using selectMode, the input will be ng-valid even when a value has not been selected (ngModel = undefined), causing 1 test to fail.

This is weird because the tests will pass, but it clearly show the problems using the docs pages. Except for the last one, I wasn't able to make the tests fail to reproduce these issues. Need help to fix them :(

### CODE REVIEW

**Comment by ansonkao** [comment]
@vmlf01 is this PR still being developed? If it's stale, I'd like to submit my own PR for the issue of the cursor moving to the end, as it's a pretty urgent bug for me. Please let me know!

**Comment by vmlf01** [comment]
@ansonkao I think it would be best to submit your PR

**Comment by edhenderson** [comment]
@ansonkao Hey, did you submit your own PR for the cursor-to-the-end-problem? LMK, thanks. E.

**Comment by ansonkao** [comment]
@edhenderson I didn't end up tackling it. There is an issue on GitHub explaining how to solve the problem, I have it written down somewhere, if you wanted to try I can dig it up!

**Comment by edhenderson** [comment]
@ansonkao If you have it that would be great. I tried something involving catching the keyUp and keyDown to retro-put the cursor back but when you delete too quickly, the Typeahead event wins the race condition.

**Comment by ansonkao** [comment]
@edhenderson found it. Have a look through these 2 links, hope it helps!

https://github.com/mgcrea/angular-strap/issues/1448
http://stackoverflow.com/questions/26263169/how-to-retain-cursor-position-when-updating-a-knockout-js-observable-in-an-exten?rq=1

**Comment by edhenderson** [comment]
:+1:

**Pull request closed without merging**
