### PR TITLE
Document usage of 'today' in datepicker maxDate and minDate.

### PR DESCRIPTION
**Pull request by brycepj**
See issue #1622 "datepicker minDate 'today' broken"

### CODE REVIEW

**Comment by mgcrea** [comment]
Landed in ee71a1e. Please follow commit message conventions next time.

**Comment by brycepj** [comment]
@mgcrea Are they documented anywhere? I looked at the `Contributing` section ahead of time and didn't see anything relevant.

**Comment by mgcrea** [comment]
see https://github.com/mgcrea/angular-strap/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by brycepj** [comment]
Nice. Thank you. Should've seen that.

**Pull request closed without merging**
