### PR TITLE
Make safeDigest() absolutely safe

### PR DESCRIPTION
**Pull request by e-oz**
It will solve [issue](https://github.com/angular/angular.js/issues/11713) with ngAnimate and in general I think it's more safe.

### CODE REVIEW

**Comment by mgcrea** [comment]
Not sure about this one, I know the performance hit would be negligible, but it might make finding bugs (like this one) harder.

**Comment by vmlf01** [comment]
Maybe at least log the error to the console?

**Comment by jamm** [comment]
@vmlf01 often e2e tests requires console.log to be empty after test, so it would make them fail.

**Comment by seldary** [comment]
So, after angular closed [the animate callback issue](https://github.com/angular/angular.js/issues/11713), I'm guessing angular-strap now doesn't support angular 1.4?

This is more to do with calling $animate than safeDigest...

**Comment by e-oz** [comment]
Can't reproduce anymore.

**Pull request closed without merging**
