### PR TITLE
fix tooltip.js click on touch screen

### PR DESCRIPTION
**Pull request by cp2587**
Fix for https://github.com/mgcrea/angular-strap/issues/2052#issuecomment-204129248

### CODE REVIEW

**Comment by DaleWebb** [comment]
Thanks, @mgcrea will have to approve this one.

Try to follow the commit conventions next time too :) https://github.com/mgcrea/angular-strap/blob/master/CONTRIBUTING.md#git-commit-guidelines

**Comment by cp2587** [comment]
Sorry about that. Do you want me to do another PR with a better commit message ?

**Comment by DaleWebb** [comment]
That would be great, cheers :+1:

**Comment by cp2587** [comment]
I created a second pull request:
https://github.com/mgcrea/angular-strap/pull/2078. Hope this one is OK.

2016-04-01 11:41 GMT+02:00 Dale Alexander Webb <notifications@github.com>:

> That would be great, cheers [image: :+1:]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgcrea/angular-strap/pull/2077#issuecomment-204329935>
>



-- 
Charles PIERRE
Founder / CTO
http://wiremind.fr/
Mail:           cpierre@wiremind.fr
Mobile:       +33 6 95 78 58 93
Wiremind, SAS.

**Pull request closed without merging**
