### PR TITLE
refactor(modal): remove unused injection: $q, $http and $templateCache

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by bstruthers** [comment]
@lookfirst heads up, mgcrea is most likely going to ask you to follow the [Contributing guidlines](https://github.com/mgcrea/angular-strap/blob/master/CONTRIBUTING.md).  Namely, change the commit message to refactor(modal): ______

**Comment by lookfirst** [comment]
@bstruthers oh forgot that... thanks!

**Comment by mgcrea** [comment]
@lookfirst, @bstruthers was talking about the commit message, not the title issue. `git commit --amend -m 'refactor(modal): remove unused injection: $q, $http and $templateCache'; git push --force` was the proper fix to apply.

Anyway, thanks! Landed in e0e8c58.

**Comment by lookfirst** [comment]
@mgcrea Sorry about that... was thinking that it would have changed the commit message too... oh well... lol...

**Pull request closed without merging**
