### PR TITLE
fix(boolean options) - fix boolean options on all directives and update tests

### PR DESCRIPTION
**Pull request by dankahle**
My force push on my boolean-attr-fix branch closed the pull request for some reason. Not sure there was a way around that as I usually have to force push my branch after rebasing on the latest master. The PR is closed, so opening a new one. I'm done with this work now, all code and tests are running fine.

Looks like my rebase with merge conflicts created a merge commit:
"Merge branch 'master' of https://github.com/mgcrea/angular-strap"

on my machine this merge has no code in it, but up here it appears to have all the code from the commits that got added in that latest master pull from base. Not sure why that appears like that. All my changes are in the commit:
"fix(boolean options): make falsy boolean options work"

### CODE REVIEW

**Comment by mgcrea** [comment]
Would be great if you could squash everything to a single commit:

Looks like you have two commits with the same name:
- https://github.com/dankahle/angular-strap/commit/f2089c51e362e870a28eb32ef4160efbf8bc94fe
- https://github.com/dankahle/angular-strap/commit/ed289fad02e41c2eaf09e95ee37af61b38de8738

**Comment by dankahle** [comment]
I don't know how to do this sadly. I get get it looking nice locally with a
squash, but when I go to push, the github complains the the sever branch is
ahead (which is is cause I squashed locally). If I force the push, it
cancels my PR and if I don't it makes me pull which adds a merge commit,
which it adds to the server commit, and then my local commit, and I end up
with at least 3 commits on the server again (grrrr). Enlighten me on how to
do this. Nearest I can see, the only way is to create another branch, get
it all right over there and push it up, then create a new PR. That might
work.




On Mon, Mar 30, 2015 at 8:28 AM, Olivier Louvignes <notifications@github.com

**Comment by dankahle** [comment]
I don't understand this rebase to master thing. I.e. I git pull base master and then rebase my work branch on master and expect my work branch to just jump on top the latests commits from your repo. But, whether or not there are merge conflicts, I end up with this merge commit, that appears to be the the summation of all the new commits from your repo, and  ... I get all the new commits from your repo. I don't understand what the merge is in there for, or why it has the summation of the commits coming in. I guess I do if there were conflicts, but even if I have conflicts, that merge doesn't seem to include any of "my" code, my conflict changes are in my own commit I believe. Can I just delete these merge commits?

Somehow I ended up with 2 commits with all my changes. I guess I'll delete the older one as well. Try to get it down to just the one commit with my changes and push that to a new branch and create a PR on that. Let me know if I'm doing something wrong. Oh and I have to rebase again now as surely there are new commits ... yep. Ok, I'll see what I can do... it'll be a new PR for sure and I'll just rebase, get your latest and cherrypick my change commit. Hopefully that will work.

**Comment by dankahle** [comment]
No, the merges have the merged code (from conflicts), they have to stay, at least the ones with conflicts resolved in them. I'll just try to get all the commits of mine at the top and squash them into one, create a new branch and PR that.

**Comment by dankahle** [comment]
gonna try a new fork

**Pull request closed without merging**
