### PR TITLE
bs checkboxgroup will now work with ng repeat

### PR DESCRIPTION
**Pull request by almondtools**

### CODE REVIEW

**Comment by iwuvjhdva** [comment]
Possible to merge?

**Comment by mgcrea** [comment]
@almondtools Could you please remove the built file (dist) and squash your commits into a single one? Thanks!

**Comment by almondtools** [comment]
I am not so familiar with git. Is the commit correct now?

By the way: Is the patch acceptable? I do not mind, if it is reworked by others, if it does not suite into the rest of the code.

**Comment by mgcrea** [comment]
The patch fails against latest 1.3, I think you should use `bs-checkbox` directly when you want to use ng-repeat. Added test related to that.

**Pull request closed without merging**
