### PR TITLE
Feature(modal): Add configurable z-index

### PR DESCRIPTION
**Pull request by palortoff**
Make Z-Index of modal and backdrop configurable to avoid interference with other elements

### CODE REVIEW

**Comment by mgcrea** [comment]
Thanks for the commit but:
1. Please remove dist files.
2. Use a lowercase only git commit message

**Comment by palortoff** [comment]
All done.
Thanks!

**Comment by bstruthers** [comment]
@palortoff looks like src/modal/modal.js.orig is still in the PR

**Comment by palortoff** [comment]
file removed

**Pull request closed without merging**
