### PR TITLE
fix(timepicker): reverse behaviour of arrows in picker mode

### PR DESCRIPTION
**Pull request by DaleWebb**
currently when you specify the arrow behaviour to be "picker",
when you press "up" it will increment the number.  This contrasts
to the keyboard button "up" which will decrement.
Now, the behaviour is the same for both the keyboard and arrow, by
making the arrow "up" decrement instead.

closes: #2086

### CODE REVIEW

**Comment by acurrieclark** [comment]
Does it not make more sense (in picker mode) for both the keyboard and arrow "up" actions to increment? When compared to the pager mode, I see why you have made the change as you have done, but in isolation it strikes me as more intuitive for up to increment and down to decrement.

**Comment by DaleWebb** [comment]
If you think where the numbers would be if you could see them listed, I imagine it would be in ascending order.  Is your argument similar to touchpad scrolling, where some people prefer to reverse the scroll?

**Comment by acurrieclark** [comment]
I know what you mean. But in my mind, pressing up would mean increasing,
rather than moving within a list. When you see the numbers in "pager" mode,
you see the list. Otherwise, the only number you see is the current time.
In that case "up" would really mean "plus".

**Comment by DaleWebb** [comment]
Hmm, can you find a website that has implemented that behaviour?  I feel that the current behaviour is what the user would expect

**Comment by acurrieclark** [comment]
It seems there are a few different take on this. But it would seem that the majority of timepickers I found have “up" as “plus” when in the mode we are describing. For example:

https://jdewit.github.io/bootstrap-timepicker/
http://ericjgagnon.github.io/wickedpicker/
http://keith-wood.name/timeEntry.html

This one does the opposite, but offers the option to change the default behaviour:

http://senthilraj.github.io/TimePicki/

I absolutely agree that if the times were listed, then a user would expect “up” to move up the list, hence decreasing the time. However, if the user is not presented with a list, I cannot help but feel that they would expect “up” to mean “plus”. On a site which used only this type of timepicker, a user would not even be used to seeing a list in the context.

Perhaps an option would be the best way forward?
All of this aside, the fact that the arrows now match the keyboard action is definitely a step in the right direction.

-- 
Alex Currie-Clark
07825346673

On 10 May 2016 at 23:37:20, Dale Alexander Webb (notifications@github.com) wrote:

Hmm, can you find a website that has implemented that behaviour? I feel that the current behaviour is what the user would expect

**Comment by mgcrea** [comment]
Agree that this should be an option.

**Comment by mgcrea** [comment]
@DaleWebb is this mergeable?

**Comment by DaleWebb** [comment]
Yeah

**Pull request closed without merging**
