### PR TITLE
feat(tooltip): Added support for bootstrap like viewport overflow adjust...

### PR DESCRIPTION
**Pull request by michaelfdeberry**
Added functionality to adjust the tooltip position so that it does not overflow the viewport. 
sample

### CODE REVIEW

**Comment by BrandonLWhite** [comment]
I was just about to open an issue for this exact problem.  It seems to me like the tooltip "auto" isn't quite taking into account all of the possibilities that it needs to be.

[Here's a plunker](http://plnkr.co/edit/Ipwhv5c443QmW8JKAaxP?p=preview) to demonstrate the problem.

**Comment by mgcrea** [comment]
Thanks for the PR, I'll check the changes asap ;-).

**Comment by gaui** [comment]
Why not use `window.innerHeight` and `window.innerWidth` instead of the dimensions of the `html` DOM element?

**Comment by mgcrea** [comment]
Thanks for the PR, #1472 was merged and it solves this issue.

**Pull request closed without merging**
