### PR TITLE
(typeahead) add trimValue feature

### PR DESCRIPTION
**Pull request by ianus1234**
The new option allows to disable the view value of the input field to be trimmed. it might be necessary if searching for several words where the request starts directly after entering a space. this space will then not be removed from the view value.

### CODE REVIEW

**Comment by mgcrea** [comment]
Could you please squash all your commits into a single one and use a proper commit message?

**Comment by qqilihq** [comment]
Hi guys, what's the state on this? I'm having problems where spaces at the end during entering a value are just stripped off, which is very annoying. Sounds like these changes could solve my issue...

**Comment by chrisguerrero** [comment]
+1

I'm waiting on this to get merged as well

**Comment by blaind** [comment]
+1

**Comment by jcassee** [comment]
+1

**Comment by rtorrero** [comment]
I just tried this, and I'm having trouble using it in combination with delayed model update. Could anyone try ng-model-options="{debounce: 500}" and confirm this? 

Without this, it seems to work correctly.

**Comment by sank** [comment]
+1
Trimming appears when you get a list from the server.
ng-model-options is the same problem.

**Pull request closed without merging**
